lauth:
  scopes:
    sync: ${LAUTH_SYNC_SCOPE_DEFINITION:false}
    definitions:
      - resource: user
        action: READ
        description: Can read user data
      - resource: user
        action: WRITE
        description: Can write user data

server:
  port: ${PORT:8081}

spring:
  application:
    name: ${APPLICATION_NAME:identity-service}

  datasource:
    url: ${DB_URL:jdbc:h2:mem:${spring.application.name};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    location: classpath:db/migration
    validate-on-migrate: true
    validate-migration-naming: true
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    baseline-version: 1
    baseline-description: Existing JPA schema

  kafka:
    bootstrap-servers: ${KAFKA_URL:kafka:9092}
    client-id: ${spring.application.name}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probe:
        enabled: true
      roles: ADMIN
      show-details: when-authorized
      show-components: when-authorized
      group:
        liveness:
          include: "livenessState"
        readiness:
          include: "readinessState"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_ENDPOINT:}